// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggzyxwseuckjiieyqryp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnenl4d3NldWNramlpZXlxcnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDY1MzksImV4cCI6MjA2MTUyMjUzOX0.5En5jkFF-zRYqN7tJCpukCVMYC94RwowH2lPx65ML40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);